cargo: update to fix build
Without it, we get the following build error:

error[E0659]: `NonZero` is ambiguous
   --> /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/common_traits-0.10.0/src/impls.rs:740:14
    |
740 |         impl NonZero for $nzsty {
    |              ^^^^^^^ ambiguous name